import { spawn } from "node:child_process";

import type { CanonicalJsonValue } from "../crypto/canonical.js";

export interface AdapterRunInput {
  readonly koId: string;
  readonly contentHash: string;
  readonly contentType: string;
  readonly content: CanonicalJsonValue;
}

export interface AdapterRunRequest {
  readonly task: string;
  readonly model: string;
  readonly inputs: readonly AdapterRunInput[];
}

export interface AdapterRunResult {
  readonly output: CanonicalJsonValue;
  readonly notes?: readonly string[];
}

export interface RunAdapter {
  readonly id: string;
  /**
   * Deterministic adapters never leave the install (no network, no model
   * call) and therefore do not require `--ack-egress`.
   */
  readonly deterministic: boolean;
  run(request: AdapterRunRequest): Promise<AdapterRunResult>;
}

export const DEFAULT_ADAPTER_ID = "anthropic";
export const DEFAULT_ANTHROPIC_MODEL = "claude-sonnet-4-5";

/**
 * Templated, offline adapter used for tests and reproducible runs. It produces
 * a structured report summarizing every input Knowledge Object without calling
 * any external model.
 */
export const deterministicAdapter: RunAdapter = {
  id: "deterministic",
  deterministic: true,
  async run(request: AdapterRunRequest): Promise<AdapterRunResult> {
    return {
      output: {
        kind: "report",
        title: request.task,
        model: request.model,
        summary: `Deterministic synthesis of ${request.inputs.length} input Knowledge Object(s).`,
        sections: request.inputs.map((input, index) => ({
          heading: `Input ${index + 1}: ${input.koId}`,
          body: `${input.contentType} (${input.contentHash})`,
        })),
      },
      notes: ["Generated by the deterministic adapter (no model call)."],
    };
  },
};

export interface AnthropicAdapterDependencies {
  readonly command?: string;
  readonly args?: readonly string[];
  readonly env?: NodeJS.ProcessEnv;
  readonly timeoutMs?: number;
  readonly runCommand?: (options: {
    readonly command: string;
    readonly args: readonly string[];
    readonly stdin: string;
    readonly timeoutMs: number;
  }) => Promise<string>;
}

export const DEFAULT_ADAPTER_TIMEOUT_MS = 120_000;

/**
 * Wraps an external Anthropic adapter command (for example the proven
 * `claude-cli-adapter.mjs`). The command receives the run request as JSON on
 * stdin and must emit an `agent_output`-shaped JSON object on stdout. Because
 * it leaves the install, callers must pass `--ack-egress`.
 */
export function createAnthropicAdapter(
  dependencies: AnthropicAdapterDependencies = {},
): RunAdapter {
  const env = dependencies.env ?? process.env;
  return {
    id: "anthropic",
    deterministic: false,
    async run(request: AdapterRunRequest): Promise<AdapterRunResult> {
      const command = dependencies.command?.trim() || env.STACY_ANTHROPIC_ADAPTER_COMMAND?.trim();
      if (!command) {
        throw new Error(
          "The anthropic adapter needs an adapter command. Set STACY_ANTHROPIC_ADAPTER_COMMAND or pass --adapter deterministic for offline runs.",
        );
      }
      const runCommand = dependencies.runCommand ?? spawnAdapterCommand;
      const stdout = await runCommand({
        command,
        args: dependencies.args ?? [],
        stdin: JSON.stringify(
          {
            task: request.task,
            model: request.model,
            input_kos: request.inputs.map((input) => ({
              ko_id: input.koId,
              content_hash: input.contentHash,
              content_type: input.contentType,
              content: input.content,
            })),
          },
          null,
          2,
        ),
        timeoutMs: dependencies.timeoutMs ?? DEFAULT_ADAPTER_TIMEOUT_MS,
      });
      return parseAdapterStdout(stdout);
    },
  };
}

export interface BuildAdapterRegistryOptions {
  readonly env?: NodeJS.ProcessEnv;
  readonly anthropic?: RunAdapter;
  readonly extra?: Readonly<Record<string, RunAdapter>>;
}

export function buildAdapterRegistry(
  options: BuildAdapterRegistryOptions = {},
): Map<string, RunAdapter> {
  const registry = new Map<string, RunAdapter>();
  registry.set(deterministicAdapter.id, deterministicAdapter);
  registry.set("anthropic", options.anthropic ?? createAnthropicAdapter({ env: options.env }));
  for (const [id, adapter] of Object.entries(options.extra ?? {})) {
    registry.set(id, adapter);
  }
  return registry;
}

export function resolveDefaultAdapterId(env: NodeJS.ProcessEnv = process.env): string {
  return env.STACY_DEFAULT_ADAPTER?.trim() || DEFAULT_ADAPTER_ID;
}

export function resolveRunAdapter(
  name: string,
  registry: ReadonlyMap<string, RunAdapter>,
): RunAdapter {
  const adapter = registry.get(name.trim().toLowerCase());
  if (!adapter) {
    const available = [...registry.keys()].join(", ");
    throw new Error(`Unknown adapter "${name}". Available: ${available}`);
  }
  return adapter;
}

function parseAdapterStdout(stdout: string): AdapterRunResult {
  let parsed: unknown;
  try {
    parsed = JSON.parse(stdout);
  } catch {
    throw new Error("Adapter did not return valid JSON output.");
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error("Adapter output must be a JSON object.");
  }
  const record = parsed as Record<string, unknown>;
  const output = (record.output ?? record) as CanonicalJsonValue;
  const notes = Array.isArray(record.notes)
    ? record.notes.filter((note): note is string => typeof note === "string")
    : undefined;
  return { output, notes };
}

async function spawnAdapterCommand(options: {
  readonly command: string;
  readonly args: readonly string[];
  readonly stdin: string;
  readonly timeoutMs: number;
}): Promise<string> {
  const child = spawn(options.command, [...options.args], { stdio: ["pipe", "pipe", "pipe"] });
  let stdout = "";
  let stderr = "";
  let timedOut = false;
  child.stdout?.setEncoding("utf8");
  child.stderr?.setEncoding("utf8");
  child.stdout?.on("data", (chunk: string) => {
    stdout += chunk;
  });
  child.stderr?.on("data", (chunk: string) => {
    stderr += chunk;
  });
  child.stdin?.end(options.stdin);

  const exitCode = await new Promise<number | null>((resolveExit, reject) => {
    const timeout = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
    }, options.timeoutMs);
    child.on("error", reject);
    child.on("close", (code) => {
      clearTimeout(timeout);
      resolveExit(code);
    });
  });
  if (timedOut) {
    throw new Error(`Adapter command timed out after ${options.timeoutMs}ms`);
  }
  if (exitCode !== 0) {
    throw new Error(`Adapter command failed with exit code ${exitCode ?? "unknown"}: ${stderr.trim()}`);
  }
  return stdout.trim();
}
